### ISSUE TITLE
Failing Uncontested Election

### ISSUE THREAD

**Issue by abugler** [nathanllww/slivka-irv#15]
IRV fails when the election is uncontested. See branch https://github.com/nathanllww/slivka-irv/tree/test_case for the new test case.

**Comment by nathanllww** [comment]
This issue was actually much broader and problematic, so I'll include here what it was.  Essentially, if only one candidate remained, IRV did not recompute tallies.  This lead to systems like "a; b,a" being marked as no confidence even when a should win.  The fix is thus somewhat straightforward: when we've eliminated all but one candidate, compute tallies one final time before declaring a winner.

Thanks for catching this, seems it could have affected a wide number of elections.
